export const KNOWN_LEADING_WORDS = [
  "vertical slice",
  "single source of truth",
  "idempotente",
  "idempotent",
  "dry run",
  "feature flag",
  "blue-green",
  "canary release",
  "tdd",
  "test driven",
  "dependency injection",
  "injeção de dependência",
  "immutable",
  "imutável",
  "memoization",
  "debounce",
  "event sourcing",
  "cqrs",
  "circuit breaker",
  "zero-downtime",
  "backward compatible",
  "retrocompatível",
  "separation of concerns",
  "separação de responsabilidades",
  "single responsibility",
  "responsabilidade única",
  "dry (don't repeat yourself)",
  "yagni",
  "kiss",
  "fail fast",
  "graceful degradation",
  "progressive disclosure",
  "leading word",
  "happy path",
  "edge case",
  "rollback",
  "rollout",
  "source of truth",
];

export const GENERIC_INSTRUCTION_PATTERNS: RegExp[] = [
  // Portuguese
  /n[ãa]o implemente tudo de uma vez/i,
  /tente ser claro/i,
  /fa[çc]a o melhor poss[íi]vel/i,
  /de forma adequada/i,
  /quando necess[áa]rio/i,
  /sempre que poss[íi]vel/i,
  /da melhor forma/i,
  /com cuidado/i,
  /de maneira eficiente/i,
  /de forma clara e objetiva/i,
  // English
  /do(n't| not) implement everything at once/i,
  /try to be clear/i,
  /do (your |the )?best/i,
  /as appropriate/i,
  /when necessary/i,
  /whenever possible/i,
  /in the best (way|manner)/i,
  /(be |work )?carefully/i,
  /efficiently and effectively/i,
  /clearly and (concisely|objectively)/i,
];

export const PLANNING_KEYWORDS: RegExp[] = [
  // Portuguese
  /crie um plano/i,
  /plano de implementa[çc][ãa]o/i,
  /gere um plano/i,
  /monte um plano/i,
  /elabore um plano/i,
  // English
  /create an? (implementation )?plan/i,
  /generate an? plan/i,
  /draft an? plan/i,
  /write (up )?an? plan/i,
  /produce an? plan/i,
];

export const CLARIFYING_QUESTION_KEYWORDS: RegExp[] = [
  // Portuguese
  /fa[çc]a pergunta/i,
  /pergunte ao usu[áa]rio/i,
  /esclare[çc]a antes/i,
  /pergunta(s)? de esclarecimento/i,
  /tire d[úu]vidas antes/i,
  // English
  /ask (the )?user/i,
  /clarifying question/i,
  /clarify (before|first)/i,
  /ask questions? before/i,
  /gather requirements? before/i,
];
